version: '3.9'

services:
  caddy:
    container_name: caddy_server
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/conf:/etc/caddy
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/conf
      - media_data:/media
      - static_data:/static
    networks:
      - saas_net

networks:
  saas_net:
    external: true

volumes:
  caddy_data:

  caddy_config:
